#!/usr/bin/env bash

if [ ! -d .git ]
then
    echo "The current directory is not a git repository!"
    exit
fi

REPOINFO=$(gh repo view --json owner,name |jq -r '.name,.owner.login')

LAST=$(gh pr list --limit 1 --state all --json number|jq '.[].number')
#LAST=2

if [ x == ${LAST}x ]
then
    echo "There is no open pull request, specify one PR number to show!"
    exit
fi

get_review_ids () {
    gh api repos/$(echo $REPOINFO|awk '{print $2}')/$(echo $REPOINFO|awk '{print $1}')/pulls/${LAST:-2}/reviews|jq '.[].id'
}


gh api graphql -f query='
{
  repository(owner: "terraform-alibabacloud-roles", name: "cf_network_base") {
    pullRequests(last: 10) {
      nodes {
        id
        number
        title
      }
    }
    id
    createdAt
    pullRequest(number: 2) {
      reviews(last: 10) {
        nodes {
          author {
            login
          }
          bodyText
          comments(last: 10) {
            nodes {
              bodyText
            }
            totalCount
          }
        }
      }
    }
  }
}'
