#!/usr/bin/env bash

if [ ! -d .git ]
then
    echo "The current directory is not a git repository!"
    exit
fi

LAST=$(gh pr list --limit 1 --state all --json number|jq '.[].number')

while getopts ":l:" Option
do
  case $Option in
    l  ) LAST=$OPTARG;;
  esac
done

shift $(($OPTIND - 1))

REPOINFO=$(gh repo view --json owner,name |jq -r '.name,.owner.login')
OWNER=$(echo $REPOINFO|awk '{print $2}')
REPO=$(echo $REPOINFO|awk '{print $1}')


template1='
{{- range $pr := .data.repository.pullRequests.nodes -}}
  {{- tablerow (printf "%v" .number) (printf "%v" .title| autocolor "green") -}}
{{- end -}}
'
template2='
{{- range $rv := .data.repository.pullRequest.reviews.nodes -}}
{{- tablerow (printf "%v" .author.login) -}}
{{- tablerow (printf "%v" .bodyText) -}}
{{- range $cm := .comments.nodes -}}
{{- tablerow (printf "%v" .bodyText) -}}
{{- end -}}
{{- end -}}
'

query='
query ($owner: String!, $name: String!, $prlast: Int!) {
  repository(owner: $owner, name: $name) {
    pullRequests(last: 10) {
      nodes {
        id
        number
        title
      }
    }
    id
    createdAt
    pullRequest(number: $prlast) {
      reviews(last: 10) {
        nodes {
          author {
            login
          }
          bodyText
          comments(last: 10) {
            nodes {
              bodyText
            }
            totalCount
          }
        }
      }
    }
  }
}'

gh api graphql -F owner="$OWNER" -F name="$REPO" -F prlast=${LAST} -f query="$query" --template="$template1"

gh api graphql -F owner="$OWNER" -F name="$REPO" -F prlast=${LAST} -f query="$query" --template="$template2"




